set tabstop=4
set shiftwidth=4
set expandtab
set number

set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'leshill/vim-json'
Plugin 'Shutnik/jshint2.vim'

Bundle 'christoomey/vim-tmux-navigator'


call vundle#end()
filetype plugin indent on

